#name: CI/CD for Microservices
#
#on:
  #push:
    #branches:
      #- master
    #paths:
      #- 'cart-cna-microservice/**'
      #- 'product-cna-microservice/**'
      #- 'search-cna-microservice/**'
      #- 'store-ui/**'
      #- 'users-cna-microservice/**'
#
#env:
  #AWS_REGION: us-east-1
  #EKS_CLUSTER_NAME: gitops-eks
#
#jobs:
  #detect-changes:
    #name: Detect Changes
    #runs-on: ubuntu-latest
    #outputs:
      #dirs: ${{ steps.directories.outputs.all_changed_files }}
      #count: ${{ steps.directories.outputs.all_changed_files_count }}
    #steps:
      #- uses: actions/checkout@v4
      #- name: Get changed directories
        #id: directories
        #uses: tj-actions/changed-files@v40
        #with:
          #dir_names: true
          #json: true
          #escape_json: false
          #quotepath: false
          #files: |
            #cart-cna-microservice/
            #product-cna-microservice/
            #search-cna-microservice/
            #store-ui/
            #users-cna-microservice/
#
  #docker-build-and-push:
    #if: needs.detect-changes.outputs.count > 0
    #name: Docker Build and Push
    #runs-on: ubuntu-latest
    #needs: [detect-changes]
    #strategy:
      #matrix:
        #dir: ${{ fromJSON(needs.detect-changes.outputs.dirs) }}
      #max-parallel: 5
      #fail-fast: false
    #steps:
      #- uses: actions/checkout@v4
#
      #- name: Login to Docker Hub
        #uses: docker/login-action@v3
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
      #- name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v1
#
      #- name: Build and Push Docker Image
        #env:
          #GITHUB_SHA: ${{ github.sha }}
        #run: |
          #cd ./${{ matrix.dir }}
          #docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dir }}:${GITHUB_SHA::7} .
          #docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dir }}:${GITHUB_SHA::7}
#
  #helm-deploy:
    #name: Helm Deploy to EKS
    #runs-on: ubuntu-latest
    #needs: [docker-build-and-push]
    #steps:
      #- uses: actions/checkout@v4
#
      #- name: Configure AWS credentials
        #uses: aws-actions/configure-aws-credentials@v1
        #with:
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: ${{ env.AWS_REGION }}
#
      #- name: Set up kubectl
        #run: |
          #aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
#
      #- name: Deploy with Helm
        #run: |
          #helm upgrade --install ${{ matrix.dir }} ./helm/${{ matrix.dir }} \
            #--set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dir }} \
            #--set image.tag=${SHORT_SHA:0:7} \
            #--namespace ${{ matrix.dir }}



name: CI/CD for Microservices

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: gitops-eks

jobs:
  docker-build-and-push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [cart-cna-microservice, product-cna-microservice, search-cna-microservice, store-ui, users-cna-microservice]
      max-parallel: 5
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          GITHUB_SHA: ${SHORT_SHA:0:7}
        run: |
          cd ./${{ matrix.service }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${SHORT_SHA:0:7} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${SHORT_SHA:0:7}

  helm-deploy:
    name: Helm Deploy to EKS
    runs-on: ubuntu-latest
    needs: [docker-build-and-push]
    strategy:
      matrix:
        service: [cart-cna-microservice, product-cna-microservice, search-cna-microservice, store-ui, users-cna-microservice]
      max-parallel: 5
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ matrix.service }} ./helm/${{ matrix.service }} \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }} \
            --set image.tag=${SHORT_SHA:0:7} \
            --namespace ${{ matrix.service }}
